services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    restart: unless-stopped

    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=dokumaelastic
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g

    ports:
      - "9200:9200"

    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data

    ulimits:
      memlock:
        soft: -1
        hard: -1

    networks:
      - deeds-net

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS -u elastic:dokumaelastic http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      retries: 10
      start_period: 40s
      timeout: 5s

volumes:
  elasticsearchdata:

networks:
  deeds-net:
    external: true
